apache/pekko-samples

.github/workflows/build-test.yml
* CI build is set up to only run for PRs
* use a simple PR to see what parts of build works today
=> baseline build

pekko-sample-distributed-workers-scala/README.md
partially migrated with #6 but still needs more work
=> add warning to pekko-sample-distributed-workers-scala README

pekko-sample-cluster-client-grpc-scala/src/main/scala/sample/cluster/client/grpc/ClusterClient.scala
* see https://github.com/apache/incubator-pekko-grpc/issues/49 for background
* this change reduces the number of implicits used
=> rework implicits in grpc sample

akka-sample-fsm-java/README.md, akka-sample-fsm-scala/README.md, akka-sample-sharding-scala/README.md
Some of the unmigrated samples have had some edits done already to their readmes - this PR fixes up some of those links
=> fix some links

.github/workflows/build-test.yml, pekko-sample-distributed-workers-scala/README.md, pekko-sample-distributed-workers-scala/build.sbt
=> fix workers sample

.github/workflows/build-test.yml, pekko-sample-cluster-docker-compose-java/LICENSE, pekko-sample-cluster-docker-compose-java/README.md, pekko-sample-cluster-docker-compose-java/build.sbt, pekko-sample-cluster-docker-compose-java/docker-compose.yml, pekko-sample-cluster-docker-compose-java/project/build.properties, pekko-sample-cluster-docker-compose-java/project/plugins.sbt, pekko-sample-cluster-docker-compose-java/scripts/test.sh, pekko-sample-cluster-docker-compose-java/src/main/java/com/example/ClusterListener.java, pekko-sample-cluster-docker-compose-java/src/main/java/com/example/ClusteringApp.java, pekko-sample-cluster-docker-compose-java/src/main/resources/application.conf, pekko-sample-cluster-docker-compose-java/src/main/resources/logback.xml
From https://github.com/apache/incubator-pekko/issues/287
java: git commit ref: 6501f62e6c79140fd623c167f90eb464bee66ec6
scala: git commit ref: 395a9a1f4fec7da39d1b0b66bc6f7f0f65180bff
=> pekko 287: Add pekko-cluster-docker-compose-java sample

.github/workflows/build-test.yml, pekko-sample-cluster-docker-compose-java/scripts/test.sh, pekko-sample-cluster-docker-compose-scala/LICENSE, pekko-sample-cluster-docker-compose-scala/README.md, pekko-sample-cluster-docker-compose-scala/build.sbt, pekko-sample-cluster-docker-compose-scala/docker-compose.yml, pekko-sample-cluster-docker-compose-scala/project/build.properties, pekko-sample-cluster-docker-compose-scala/project/plugins.sbt, pekko-sample-cluster-docker-compose-scala/scripts/test.sh, pekko-sample-cluster-docker-compose-scala/src/main/resources/application.conf, pekko-sample-cluster-docker-compose-scala/src/main/resources/logback.xml, pekko-sample-cluster-docker-compose-scala/src/main/scala/com/example/ClusterListener.scala, pekko-sample-cluster-docker-compose-scala/src/main/scala/com/example/ClusteringApp.scala, pekko-sample-cluster-kubernetes-scala/scripts/test.sh, pekko-sample-cluster-kubernetes-scala/scripts/test_docker_desktop.sh
https://github.com/apache/incubator-pekko/issues/287
=> Pekko #287: Migrate docker compose scala

pekko-sample-cluster-docker-compose-java/README.md, pekko-sample-cluster-docker-compose-java/build.sbt, pekko-sample-cluster-docker-compose-scala/README.md, pekko-sample-cluster-docker-compose-scala/build.sbt, pekko-sample-cluster-java/build.sbt, pekko-sample-cluster-java/pom.xml, pekko-sample-cluster-kubernetes-java/README.md, pekko-sample-cluster-kubernetes-java/pom.xml, pekko-sample-cluster-kubernetes-scala/README.md, pekko-sample-cluster-kubernetes-scala/build.sbt, pekko-sample-cluster-scala/build.sbt, pekko-sample-distributed-data-java/build.sbt, pekko-sample-distributed-data-scala/build.sbt, pekko-sample-distributed-workers-scala/build.sbt, pekko-sample-fsm-java/pom.xml, pekko-sample-fsm-scala/build.sbt, pekko-sample-kafka-to-sharding-scala/build.sbt, pekko-sample-persistence-dc-java/pom.xml, pekko-sample-persistence-dc-scala/build.sbt, pekko-sample-persistence-java/pom.xml, pekko-sample-persistence-scala/build.sbt, pekko-sample-sharding-java/build.sbt, pekko-sample-sharding-java/killrweather-fog/pom.xml, pekko-sample-sharding-java/killrweather/pom.xml, pekko-sample-sharding-scala/build.sbt
https://github.com/apache/incubator-pekko-samples/issues/41
=> upgrade scala and logback

.github/workflows/publish-nightly.yml, docs-gen/build.sbt
Needed for pekko core documentation
=> Publish more docs

pekko-sample-cluster-client-grpc-java/pom.xml, pekko-sample-cluster-client-grpc-scala/build.sbt, pekko-sample-cluster-client-grpc-scala/project/plugins.sbt, pekko-sample-cluster-docker-compose-java/build.sbt, pekko-sample-cluster-docker-compose-scala/build.sbt, pekko-sample-cluster-java/build.sbt, pekko-sample-cluster-java/pom.xml, pekko-sample-cluster-kubernetes-java/pom.xml, pekko-sample-cluster-kubernetes-scala/build.sbt, pekko-sample-cluster-scala/build.sbt, pekko-sample-distributed-data-java/build.sbt, pekko-sample-distributed-data-scala/build.sbt, pekko-sample-distributed-workers-scala/build.sbt, pekko-sample-fsm-java/pom.xml, pekko-sample-fsm-scala/build.sbt, pekko-sample-kafka-to-sharding-scala/build.sbt, pekko-sample-kafka-to-sharding-scala/project/plugins.sbt, pekko-sample-persistence-dc-java/pom.xml, pekko-sample-persistence-dc-scala/build.sbt, pekko-sample-persistence-java/pom.xml, pekko-sample-persistence-scala/build.sbt, pekko-sample-sharding-java/build.sbt, pekko-sample-sharding-java/killrweather-fog/pom.xml, pekko-sample-sharding-java/killrweather/pom.xml, pekko-sample-sharding-scala/build.sbt
based on https://cwiki.apache.org/confluence/display/PEKKO/Testing+with+Pekko+Snapshot+Jars
=> upgrade snapshot versions

docs-gen/project/plugins.sbt
relates to https://github.com/apache/incubator-pekko-sbt-paradox/pull/73
=> upgrade sbt plugin

pekko-sample-distributed-data-java/src/main/resources/application.conf, pekko-sample-distributed-workers-scala/src/main/resources/application.conf, pekko-sample-kafka-to-sharding-scala/processor/src/main/resources/application.conf, pekko-sample-persistence-dc-java/src/main/resources/application.conf, pekko-sample-persistence-dc-scala/src/main/resources/application.conf, pekko-sample-sharding-java/killrweather/src/main/resources/application.conf, pekko-sample-sharding-scala/killrweather/src/main/resources/application.conf
=> fix class name for SplitBrainResolverProvider

pekko-sample-persistence-dc-java/README.md, pekko-sample-persistence-dc-java/src/main/java/sample/persistence/res/MainApp.java, pekko-sample-persistence-dc-java/src/main/java/sample/persistence/res/counter/ThumbsUpHttp.java, pekko-sample-persistence-dc-scala/README.md, pekko-sample-persistence-dc-scala/src/main/scala/sample/persistence/res/MainApp.scala, pekko-sample-persistence-dc-scala/src/main/scala/sample/persistence/res/counter/ThumbsUpHttp.scala
Fix README.me with the correct class name and ports
=> Fix main class and ports errors

README.md
* turns out that we have different licenses for our samples
* 1 is MIT licensed
* some as CC0 licensed
* some are Apache licensed
* at least 1 has no LICENSE file
=> license info

pekko-sample-cluster-client-grpc-scala/project/plugins.sbt, pekko-sample-kafka-to-sharding-scala/project/plugins.sbt
Latest pekko-grpc has a different artifact name for the sbt plugin
=> Update to latest pekko-grpc-sbt-plugin snapshot

pekko-sample-cluster-client-grpc-java/pom.xml, pekko-sample-distributed-workers-scala/build.sbt, pekko-sample-persistence-dc-java/pom.xml, pekko-sample-persistence-dc-scala/build.sbt
based on https://cwiki.apache.org/confluence/display/PEKKO/Testing+with+Pekko+Snapshot+Jars
=> use latest pekko snapshot versions

pekko-sample-cluster-client-grpc-java/pom.xml, pekko-sample-cluster-client-grpc-scala/project/plugins.sbt, pekko-sample-cluster-docker-compose-java/LICENSE, pekko-sample-cluster-docker-compose-scala/LICENSE, pekko-sample-kafka-to-sharding-scala/project/plugins.sbt, pekko-sample-persistence-dc-java/pom.xml, pekko-sample-persistence-java/pom.xml
* can remove snapshot repo support in most samples
* junit 4.13.2
=> grpc 1.0.0 release

pekko-sample-cluster-java/src/main/java/sample/cluster/simple/App.java, pekko-sample-cluster-java/src/main/java/sample/cluster/stats/App.java, pekko-sample-cluster-java/src/main/java/sample/cluster/stats/AppOneMaster.java, pekko-sample-cluster-java/src/main/java/sample/cluster/transformation/App.java
=> fix pekko property names

.github/workflows/build-test.yml, .github/workflows/format.yml, .github/workflows/publish-nightly.yml, .scalafmt.conf, docs-gen/build.sbt, docs-gen/project/PekkoSamplePlugin.scala, docs-gen/project/plugins.sbt
relates to https://github.com/apache/incubator-pekko-site/pull/36
=> remove doc version

pekko-sample-grpc-kubernetes-scala/grpc-service/src/main/scala/com/example/helloworld/GreeterServer.scala, pekko-sample-grpc-kubernetes-scala/http-to-grpc/src/main/scala/com/example/helloworld/HttpToGrpc.scala
ActorMaterializer is deprecated
=> remove unused imports

docs-gen/project/PekkoSamplePlugin.scala, docs-gen/project/build.properties, docs-gen/project/project-info.conf, pekko-sample-cluster-client-grpc-scala/project/build.properties, pekko-sample-cluster-docker-compose-java/project/build.properties, pekko-sample-cluster-docker-compose-scala/project/build.properties, pekko-sample-cluster-java/project/build.properties, pekko-sample-cluster-kubernetes-scala/project/build.properties, pekko-sample-cluster-scala/project/build.properties, pekko-sample-distributed-data-java/project/build.properties, pekko-sample-distributed-data-scala/project/build.properties, pekko-sample-distributed-workers-scala/project/build.properties, pekko-sample-fsm-java/README.md, pekko-sample-fsm-scala/README.md, pekko-sample-fsm-scala/project/build.properties, pekko-sample-grpc-kubernetes-scala/project/build.properties, pekko-sample-kafka-to-sharding-scala/project/build.properties, pekko-sample-persistence-dc-scala/project/build.properties, pekko-sample-persistence-scala/project/build.properties, pekko-sample-sharding-java/project/build.properties, pekko-sample-sharding-scala/project/build.properties
* also sbt 1.9.7
* update GitHub link to point to this repo instead of main pekko one
=> fix links to source files

pekko-sample-cluster-java/README.md, pekko-sample-cluster-scala/README.md, pekko-sample-cluster-scala/src/main/scala/sample/cluster/stats/App.scala, pekko-sample-cluster-scala/src/main/scala/sample/cluster/stats/AppOneMaster.scala, pekko-sample-cluster-scala/src/main/scala/sample/cluster/transformation/App.scala
=> fix incorrectly prefixed config names

NOTICE
see https://github.com/apache/incubator-pekko/pull/1009
=> add incubating to NOTICE

docs-gen/project/PekkoSamplePlugin.scala
see https://github.com/apache/pekko/pull/1216
=> remove incubator notice

pekko-sample-cluster-client-grpc-scala/project/plugins.sbt, pekko-sample-cluster-java/project/plugins.sbt, pekko-sample-cluster-scala/project/plugins.sbt, pekko-sample-distributed-data-java/project/plugins.sbt, pekko-sample-distributed-data-scala/project/plugins.sbt
=> chore: update sbt-multi-jvm

.github/workflows/build-test.yml, .github/workflows/format.yml, .github/workflows/publish-nightly.yml, .scalafmt.conf
=> Update CI actions

.github/workflows/build-test.yml
see #119 
This is a temporary step to unblock other work.
=> CI: skip minikube based tests
